### ISSUE TITLE
Missing instruction on how to contribute

### ISSUE THREAD

**Issue by frog32** [dmulcahey/zha-device-handlers#1]
I would love to contribute data for the following devices. Is it possible to come up with a guide on how to collect the needed data?

- Xiaomi Mijia Temperature and Humidity sensor (the round one without air pressure)
- Xiaomi Mijia Button (round)
- Xiaomi Mijia Motion Detection

**Comment by dmulcahey** [comment]
Best I can do atm is say use the existing Aqara ones as a guide. https://github.com/dmulcahey/zha-device-handlers/blob/009409765e375797aa75a1e7301ff386413961ae/zhaquirks/xiaomi/aqara_body_sensor.py#L100 Those comments are directly from HA when you pair a device. Grab those lines and use the rest as a guide. I’ll try to create some docs soon...
