### ISSUE TITLE
Smartthings moisture sensor v1 not returning battery (0.96)

### ISSUE THREAD

**Issue by ryanwinter** [dmulcahey/zha-device-handlers#116]
I'm sure this was working in the past, however now I'm seeing 'unknown' battery for this device since upgrading to 0.96.

When I query the 'battery_voltage' attribute, I get 26 which indicates 100%.

**Comment by dmulcahey** [comment]
Can I have the signature for the device?

**Comment by ryanwinter** [comment]
here!
manufacturer=Smartthings
model=moisturev4

input_clusters=[0, 1, 3, 15, 32, 1026, 1280]
output_clusters=[25]

Ah, so it looks like the same signature as the motion, however the model is different.

**Comment by dmulcahey** [comment]
Can I have a screenshot of the device card too in the config panel? Sorry, should have asked for that before.

**Comment by ryanwinter** [comment]
Do you mean this?

![Screenshot_20190719-112043](https://user-images.githubusercontent.com/10238039/61557293-b559a980-aa18-11e9-96f2-ee050b9f04f3.png)

**Comment by dmulcahey** [comment]
yes. Thanks!

**Comment by dmulcahey** [comment]
wanna try #117 and let me know if it fixes your issue?

**Comment by ryanwinter** [comment]
> wanna try #117 and let me know if it fixes your issue?

Sorry for slow reply, was out for the weekend, LGTM.
