### ISSUE TITLE
Aqara humididy don't work with the last update

### ISSUE THREAD

**Issue by Nemesis24** [dmulcahey/zha-device-handlers#139]
![Sans titre](https://user-images.githubusercontent.com/25956796/63571074-6951d580-c57f-11e9-8dc8-c78a933bfd66.png)

**Comment by dmulcahey** [comment]
So, I’m not sure what’s actually wrong because I can’t read the card... can you elaborate?

**Comment by Nemesis24** [comment]
HA don't receive humidity value
