### ISSUE TITLE
Aqara Cube Orientation Descriptions are off

### ISSUE THREAD

**Issue by tube0013** [dmulcahey/zha-device-handlers#148]
The Event Descriptions have the orientation of the cube off for the knock and slide events.

https://youtu.be/XTOeOap0uvs

**Comment by dmulcahey** [comment]
looks like there are multiple models for this. we need alternate mappings for these: https://github.com/dmulcahey/zha-device-handlers/blob/3236ff117c578b022760b3eaaab0e67819730005/zhaquirks/xiaomi/aqara/cube_aqgl01.py#L63

**Comment by tube0013** [comment]
![image](https://user-images.githubusercontent.com/11084412/65074786-82258f00-d963-11e9-908f-9f89f5628d3e.png)

It looks like it's essentially flipped upside down upside down is now upright and left is now right and vice versa.
