### ISSUE TITLE
Philips Remote DIM_DOWN typo?

### ISSUE THREAD

**Issue by koebbe** [dmulcahey/zha-device-handlers#175]
https://github.com/dmulcahey/zha-device-handlers/blob/833ee24710496d317a03b0f0b9f61df31291d75b/zhaquirks/philips/rwl021.py#L137

It seems that it should be:
`ARGS: [1, 30, 9],`

**Comment by dmulcahey** [comment]
Good catch. I’ll fix it in the next release.
