### ISSUE TITLE
triple click don't work (WXKG11LM)

### ISSUE THREAD

**Issue by Nemesis24** [dmulcahey/zha-device-handlers#177]
![Sans titre](https://user-images.githubusercontent.com/25956796/66848436-5d7a0280-ef75-11e9-9d5e-538bbd5e9550.png)

**Comment by dmulcahey** [comment]
I'm confused here... in your other issue: #173 it appears fine. nothing has changed in between... did you change something locally?

**Comment by Nemesis24** [comment]
I didn't change anything, but i see that the battery was added so i think there is some changes, no?

**Comment by dmulcahey** [comment]
There haven’t been any releases.

**Comment by Nemesis24** [comment]
Is it possible that in this commit:
https://github.com/home-assistant/home-assistant/commit/1087abd3b52f73640b189946e9cabdc0887e2410#diff-6aa1806cad190b7724f24144c9210a37 

the file:

homeassistant/components/zha/.translations/fr.json

the line: 

"remote_button_triple_press": "Bouton\"{sous-type}\" \u00e0 trois clics"

must have {subtype} and not {sous-type}

i think this is the reason ...
Thank you.

**Comment by dmulcahey** [comment]
fixed by #183
