### ISSUE TITLE
Yale Real Living SYDL220 (Australian version of YRL220): Battery drains in days

### ISSUE THREAD

**Issue by thimic** [dmulcahey/zha-device-handlers#186]
Hi,

I have the Yale Real Living SYDL220 lock, connected to a Raspbee hat using the ZHA component in Home Assistant. The Raspberry Pi running Home Assistant is located about 1m away from the door lock, so signal strength should not be an issue.

When not using the Lock’s Zigbee module (ZBM1), the battery lasts for months. When connecting the lock to my Home Assistant setup through the Lovelace UI, the battery drains within a few days. I am new to Zigbee devices and don’t quite know where to start with regard to debugging this. My guess is that the lock never goes to sleep, though that’s really just a hunch. There is a separate Zigbee setup in the apartment with Philips Hue lights and a Hue Bridge, though I have no idea if this might cause issues. 

I have tried unpairing the lock and re-pairing it multiple times, seemingly to no effect. I have also flashed the Raspbee with the most recent firmware.

Additionally, the lock shows up in Home Assistant with two battery sensors, none of which are working. And the lock does not report its state in a manner that Home Assistant recognises.

I think I have found a cluster attribute that reflects the lock’s state, though none of the long list of battery attributes seem to produce a value.

Any help on this appreciated. I’m happy to provide any information that might be needed to figure this out. The battery drain especially is a bit painful.

Thanks,
Michael

![6AC26746-9EA1-48FE-A313-61995A67D86D](https://user-images.githubusercontent.com/9880865/67850969-5571b380-fb6e-11e9-8d70-7935eea0b15b.jpeg)
![1FFB7EE5-503B-4CCB-8691-740C9E385E28](https://user-images.githubusercontent.com/9880865/67850970-560a4a00-fb6e-11e9-9106-93a68130073b.jpeg)
![0C762597-5F20-4CAF-94C1-FAD2162EC7A4](https://user-images.githubusercontent.com/9880865/67850971-560a4a00-fb6e-11e9-9548-110a5b4505b9.jpeg)
![3F3BA416-E4C0-4420-AC21-632122C4747B](https://user-images.githubusercontent.com/9880865/67850972-560a4a00-fb6e-11e9-9b4b-bb52de6a42d9.jpeg)

**Comment by dmulcahey** [comment]
This issue should be in home assistant. The quirk for this doesn't affect this. Can you move this issue to the home assistant repo and do the following: remove the device from the ZHA config UI, wait 5 minutes and then re-add it. Take the entire contents of the device adding panel's console and attach it to the ticket.

**Comment by thimic** [comment]
Thanks @dmulcahey. I'll do that today and close this issue ones done.

**Comment by thimic** [comment]
This is now done. See [Home Assistant issue](https://github.com/home-assistant/home-assistant/issues/28462).
