### ISSUE TITLE
Slow startup with xbee

### ISSUE THREAD

**Issue by Shulyaka** [dmulcahey/zha-device-handlers#194]
When an xbee or xbee3 device is added to HA, it causes startup time to significantly increase (by about 1 minute). Probably something is waiting for a timeout.
I plan to also look at it myself later.

**Comment by Adminiuga** [comment]
I think it because it shows as a multi endpoint `on_off` cluster device so HA queries on_off state for each endpoint?

**Comment by Shulyaka** [comment]
It's something more complicated than that. It looks like it queries something and waits for the response which it wouldn't get. I will investigate a bit later when I have some time.
