### ISSUE TITLE
xiaomi battery levels reporting incorrectly 

### ISSUE THREAD

**Issue by Nemesis24** [dmulcahey/zha-device-handlers#215]
I've change all my batteries, and my new ones are beetween 55 and 67% after 2 days, and was like beetween 75 et 85% when i change them.

**Comment by Nemesis24** [comment]
After 4 days beetween 43 and 55%.

**Comment by dmulcahey** [comment]
hopefully fixed by #208

**Comment by Nemesis24** [comment]
It's not fixed

**Comment by dmulcahey** [comment]
It hasn’t been deployed yet. It will be in .104 of home assistant

**Comment by Nemesis24** [comment]
ok sorry, but it has been deployed on zha-quirks 0.0.30 and on hassio 0.103.6 or i say some mistakes ??

**Comment by Nemesis24** [comment]
with 0.104.0b0 it's the same thing

**Comment by Adminiuga** [comment]
what is the same thing? reporting 75%-85% for the brand new battery?

**Comment by Nemesis24** [comment]
yes exactly

**Comment by Adminiuga** [comment]
@dmulcahey any plans to push new version of zha-device-handlers prior the release?
