### ISSUE TITLE
SmartThings devices' ias_zone appear as moisture sensor device_class

### ISSUE THREAD

**Issue by brettp** [dmulcahey/zha-device-handlers#228]
The ST Motion Sensor and Multipurpose Sensor both have an ias_zone that is incorrectly showing up as a moisture sensor device_class. This is possibly related to #170 

You can override this in the Home Assistant UI, but that is a pain for many devices.

**Comment by dmulcahey** [comment]
This was fixed by #226 in the last release of the lib and will be in the next release of HA.
