### ISSUE TITLE
AQARA switch  WXKG03LM 2016 no events

### ISSUE THREAD

**Issue by albalaing** [dmulcahey/zha-device-handlers#254]
There is a problem with the AQARA WXKG03LM 2016 switch that is identified as lumi.sensor_86sw1. He registers without problems and uses the Quirk zhaquirks.xiaomi.aqara.remote_b186acn01.
But when I press it I can't get him to detect anything. I have observed that this interrupt uses cluster 6 OnOff to notify that it has been pressed. And the following messages appear:

[zigpy_deconz.uart] Frame received: 0x17a10031002a00220200000104a7823dca8301008d150001040106000b00182f0a000010010000100000afefa3000102c3
[zigpy_deconz.api] APS data indication response: [42, 34, <DeconzAddress address_mode = ADDRESS_MODE.NWK address = 0x0000>, 1, <DeconzAddress address_mode = ADDRESS_MODE.NWK_AND_IEEE address = 0x82a7>, b, 260, 6, 1, 260, 6, 6 x18 / \ n \ x00 \ x00 \ x10 \ x01 \ x00 \ x00 \ x10 \ x00 ', 0, 175, 239, 163, 0, 1, 2, -61]
[zigpy.device] Ignoring message (b'182f0a0000100100001000 ') on cluster 6: unknown endpoint or cluster id:' No cluster ID 0x0006 on (00: 15: 8d: 00: 01: 83: ca: 3d, 1) '
[zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode = ADDRESS_MODE.NWK_AND_IEEE address = 0x82a7>, ep: 1, profile: 0x0104, cluster_id: 0x0006, data: b'182f0a0000100100001000
I tried to add the cluster 6 OnOff to the Quirk but I have not succeeded.

**Comment by tehspede** [comment]
Hi! I seem to have the same problem, no events under zha_event.

**Comment by radu022003** [comment]
using the Sonoff Zigbee 3.0 USB Dongle Plus V2 I can pair my 2 WXKG03LM devices but when I press the button there is no zha_event
