### ISSUE TITLE
Add codestyle/linting instruction to the Contribution Guidelines 

### ISSUE THREAD

**Issue by majkrzak** [dmulcahey/zha-device-handlers#262]
It is not to easy to prepare properly formed pull request due to lack of the code style. You will only get "failure" from travis and have to sneak through the messages. Then you will find the mysterious `check_format` script that is only pretending to "fix" the file while in real doing nothing due to the `--check` flag.

/zha-device-handlers/CONTRIBUTING.md

**Comment by dmulcahey** [comment]
All code is formatted with black. The check format script just ensures that code is formatted with black. Instructions for editors can be found here: https://github.com/psf/black#editor-integration Feel free to open a PR adding that if not I'll do it when time permits.
