### ISSUE TITLE
Xiaomi Mijia Tempearature and Humidity sensor does not create any clusters

### ISSUE THREAD

**Issue by frog32** [dmulcahey/zha-device-handlers#28]
I am trying to gather all the data required to support this device. However my zigbee.db file only shows the following for the successfully paired device:

Devices shows nwk 12370 and status 2
Endpoints shows 3 entries with endpoint_id 1, 2 and 3 status 0 but no profile_id or profile_type
clusters, output_clusters and attributes does not contain anything for that node.

Is it possible that those devices are not using ZHA and are simply sending some zigbee messages to report temperature and humidity?
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L348 seems to hint at that.

**Comment by dmulcahey** [comment]
@frog32 those errors are all in bellows / Zigpy and they tend to happen with Xiaomi devices. Do me a favor please. Set zigpy: debug in your HA log config and attach the quirks matching debug logs here too please. You can get them by restarting HA after you make the logging change.

**Comment by frog32** [comment]
2019-01-27 17:36:01 DEBUG (MainThread) [zigpy.quirks] Considering <class 'zigpy.quirks.xiaomi.TemperatureHumiditySensor'>
2019-01-27 17:36:01 DEBUG (MainThread) [zigpy.quirks] Found custom device replacement for 00:15:8d:00:01:56:a7:ad: <class 'zigpy.quirks.xiaomi.TemperatureHumiditySensor'>

Let me know if you need anything else.

**Comment by dmulcahey** [comment]
That’s what I suspected. You have Mija sensors and you’re getting OOTB Zigpy quirks. Not mine. I don’t have support for Mija devices yet. I’ll add it to my list.

**Comment by dmulcahey** [comment]
Ordered contact, temp / humidity and a button today. Should be here in a couple weeks. Shouldn’t be long after that!

**Comment by dmulcahey** [comment]
They're here... hopefully this weekend i'll have some time to play with these.

**Comment by dmulcahey** [comment]
will be in next release
