### ISSUE TITLE
Hue dimmer (rwl020) off short press

### ISSUE THREAD

**Issue by jrbenito** [dmulcahey/zha-device-handlers#286]
Hi,

I have Hue Dimmer controller integrated in Hass Core via ZHA and Bellows (zigpy). The quirk is set to a [long press of the Off button as show here](https://github.com/dmulcahey/zha-device-handlers/blob/5c726a717a4d1dc3930b177f346e852bede9ee63/zhaquirks/philips/rwl021.py#L117). However it seems device is sending this on the short press and not sending any long press for the Off button. The event on Hass is:

```
{
    "event_type": "zha_event",
    "data": {
        "unique_id": "xx:xx:xx:xx:xx:1:0x0006",
        "device_ieee": "xx:xx:xx:xx",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "off_with_effect",
        "args": [
            0,
            0
        ]
    },
    "origin": "LOCAL",
    "time_fired": "2020-03-05T05:49:25.119524+00:00",
    "context": {
        "id": "xxxxxxxxxxxx",
        "parent_id": null,
        "user_id": null
    }
}
```
Based on quirk code, it should be `long press` with no args but it is `short press` with `args [0,0]`.

This hue dimmer is with latest firmware (upgraded using Hue bridge before paring dimmer with ZHA).

Thanks.

**Comment by dmulcahey** [comment]
whoops... thanks for the report!
