### ISSUE TITLE
Xiaomi Aquara T1 Lux Sensor - Battery values

### ISSUE THREAD

**Issue by walthowd** [dmulcahey/zha-device-handlers#301]
This is the join log for the Xiaomi Aqara T1 Lux sensor. Lux values appear to work, no battery information reported. 

![Screenshot 2020-03-13 16 30 02](https://user-images.githubusercontent.com/864569/76660864-ea86af00-6547-11ea-9104-771a157ceb98.png)

Join log:
https://paste.ubuntu.com/p/23GHfsXYFt/

**Comment by walthowd** [comment]
Battery is a CR 2450 3V

**Comment by dmulcahey** [comment]
You on the beta?

**Comment by walthowd** [comment]
No, but can upgrade.

**Comment by dmulcahey** [comment]
Pretty sure this works on beta

**Comment by dmulcahey** [comment]
https://github.com/dmulcahey/zha-device-handlers/pull/277/files

**Comment by walthowd** [comment]
I will upgrade and try. Sorry, I forgot to look for recent commits on this one.

**Comment by dmulcahey** [comment]
No reason to be sorry!!!

**Comment by walthowd** [comment]
Works perfectly in beta after re-pairing! Thank you!
