### ISSUE TITLE
Samjin button signature

### ISSUE THREAD

**Issue by Socalix** [dmulcahey/zha-device-handlers#43]
Samjin button apparently has versions with and without `DIAGNOSTICS_CLUSTER_ID` in the input_clusters here:
https://github.com/dmulcahey/zha-device-handlers/blob/master/zhaquirks/samjin/button.py#L69

Mine happens to be without it, so the quirk is not being applied by HA.
Is there a way to define 2 possible signatures or would we need to have a copy of this quirk with a different signature?

**Comment by dmulcahey** [comment]
Not yet, but I am pushing for it

**Comment by ryanwinter** [comment]
I also have the button without the DIAGNOSTICS_CLUSTER_ID as an input. Should I submit a PR with the additional button signiture?

**Comment by dmulcahey** [comment]
Nah, I’ll add it to the next release

**Comment by dmulcahey** [comment]
#55 will be in next release. Please test it if you can and ensure it works.

**Comment by Socalix** [comment]
@dmulcahey #55 looks good. Thank you!
