### ISSUE TITLE
Support for lumi.sensor_smoke

### ISSUE THREAD

**Issue by Nemesis24** [dmulcahey/zha-device-handlers#45]
t will be very fine to support lumi.sensor_smoke
I can help if you explain me !
Thank you.

**Comment by Adminiuga** [comment]
Do you have a link to product? 
Xiaomi smoke detectors work out of the box though, unless anything changed with the latest release.

**Comment by Nemesis24** [comment]
https://www.gearbest.com/alarm-systems/pp_615081.html?lkid=10368929

Yes it works fine, but we can have the battery type, and battery %, .

**Comment by dmulcahey** [comment]
Please provide the simple descriptors for the device.

**Comment by prairiesnpr** [comment]
This should be fixed by https://github.com/dmulcahey/zha-device-handlers/pull/46

**Comment by dmulcahey** [comment]
@Nemesis24 please confirm

**Comment by Nemesis24** [comment]
It's ok !!

**Comment by Nemesis24** [comment]
> Please provide the simple descriptors for the device.

<SimpleDescriptor endpoint=1 profile=260 device_type=1026 device_version=1 input_clusters=[0, 3, 18, 1280, 12, 1] output_clusters=[25]>
