### ISSUE TITLE
Add guide on how to create ZHA Device Handlers similar to guide for Zigbee-Shepherd Converters

### ISSUE THREAD

**Issue by Gamester17** [dmulcahey/zha-device-handlers#49]
Background: Zigbee2mqtt project has written a great guide on how to add support for new devices by creating Zigbee-Shepherd Converters for the Zigbee2mqtt project, which I understand is a similar concept to that of ZHA Device Handlers for Home Assistant.

See http://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html 

Suggestion: Maybe it could be a good idea to copy ideas from that guide to make a similar guide for how to go about step-by-step to create ZHA Device Handlers for Home Assistant and host that in this repo as part of its documentation?

**Comment by dmulcahey** [comment]
there already is one: https://github.com/dmulcahey/zha-device-handlers/blob/master/CONTRIBUTING.md feel free to PR a link to it into the readme. I'd like to set something up w/ GH pages or the wiki but I haven't had the time to do it.
