### ISSUE TITLE
Xiaomi Magic Cube 180 degree flip

### ISSUE THREAD

**Issue by cgarwood** [dmulcahey/zha-device-handlers#5]
A thread on the SmartThings community claims the magic cube is able to tell the difference between 90 degree an 180 degree flips. Would love to see this exposed :)

https://community.smartthings.com/t/release-xiaomi-magic-cube-controller-advanced-dth/85481

**Comment by dmulcahey** [comment]
try https://github.com/dmulcahey/zha-device-handlers/commit/55f37cfc1d9ca21a246f38735184c46161dcaf85 and let me know if you like it

**Comment by dmulcahey** [comment]
Fixed by 
https://github.com/dmulcahey/zha-device-handlers/commit/55f37cfc1d9ca21a246f38735184c46161dcaf85
