### ISSUE TITLE
Xiaomi Magic Cube Orientation

### ISSUE THREAD

**Issue by cgarwood** [dmulcahey/zha-device-handlers#6]
Currently the magic cube fires events `knock_1`, `knock_2`, etc through `knock_6` depending on the cube orientation. Same for slide.

It may be better in the long run to just fire a simple `knock` or `slide` event and include an extra `orientation` key in the `event_data` - that way you only have 1 event to check for if you don't care about orientation

**Comment by dmulcahey** [comment]
try https://github.com/dmulcahey/zha-device-handlers/commit/55f37cfc1d9ca21a246f38735184c46161dcaf85 and let me know if you like it for this

**Comment by dmulcahey** [comment]
fixed by https://github.com/dmulcahey/zha-device-handlers/commit/55f37cfc1d9ca21a246f38735184c46161dcaf85
