### ISSUE TITLE
Xiaomi AQARA Switch aq3 with gyro (WXKG12LM) not well recognized

### ISSUE THREAD

**Issue by snail59** [dmulcahey/zha-device-handlers#78]
Hello,

This model is recognized as "lumi.sensor_swit", while it is a "lumi.sensor_switch.aq3".
Its signature is 
```
[0x6497:1] Discovered endpoint information: <SimpleDescriptor endpoint=1 profile=260 device_type=24321 device_version=1 input_clusters=[0, 18, 6, 1] output_clusters=[0]>
[0x6497:1] Manufacturer: LUMI
[0x6497:1] Model: lumi.sensor_swit
```

In zhaquirks/xiaomi/aqara/sensor_switch_aq3.py, modifying the line 
`'model': 'lumi.sensor_switch.aq3', `
to
`'model': 'lumi.sensor_swit'`
solves the issue.

I do not know if this is a good correction. 
The model seems truncated for whatever reason and THIS is maybe the real problem.

Again, let me know if and how I could help.

**Comment by dmulcahey** [comment]
Mine matches the first model. I wish Xiaomi would get their act together. We’ll have to duplicate this to support both models... Sigh 😔
